punch-mission/punchbowl

docs/source/conf.py
pyproject.toml

Fix versions in docs to not be super long

fix versions in docs

---

punchbowl/level3/f_corona_model.py
punchbowl/level3/tests/test_f_corona_model.py
pyproject.toml

Adds a new F corona model generation algoirthm 
Tests were updated. 
Changed the f corona model generation completely. 
Closes #154

add new f corona model generation algorithm

---

punchbowl/level1/flow.py
punchbowl/level1/psf.py

Update psf correction to the new regularizepsf version
Closes #288

update psf to new regularizepsf

---

punchbowl/level1/alignment.py
punchbowl/level1/despike.py
punchbowl/level1/destreak.py
punchbowl/level1/initial_uncertainty.py
punchbowl/level1/psf.py
punchbowl/level1/quartic_fit.py
punchbowl/level1/sqrt.py
punchbowl/level1/stray_light.py
punchbowl/level1/vignette.py
punchbowl/level2/bright_structure.py
punchbowl/level2/merge.py
punchbowl/level2/polarization.py
punchbowl/level3/f_corona_model.py
punchbowl/level3/polarization.py
punchbowl/level3/stellar.py
punchbowl/prefect.py

Adds debug mode
None
We use `punch_task` now instead of just `task` as a decorator. 
None

add debug mode

---

punchbowl/level3/stellar.py

- fixes the call of remove starfield
*Please list tasks to complete this PR.*
*How does this PR verify the code works correctly?*
*Document any breaking changes from this PR.*
*Link the issues related to this PR.*

fix call of remove starfield

---

punchbowl/data/meta.py
punchbowl/level2/flow.py
punchbowl/level3/flow.py
punchbowl/level3/low_noise.py

Update the low noise generation code

update low noise generation

---

punchbowl/level3/f_corona_model.py

Improve f corona flow generation

---

punchbowl/data/io.py

flips quicklook data vertically to the expected spatial orientation

---

punchbowl/level3/f_corona_model.py
punchbowl/level3/motion_filter.py

Merge early and often! 
`Fix sign for data smoothing` should improve the outlier removal for the F-corona estimation
* See what CI does
F-corona output will be different
None

Prep work for secondary starfield removal, plus fix for F-corona estimation

---

punchbowl/data/meta.py
punchbowl/data/tests/test_meta.py
punchbowl/data/wcs.py
pyproject.toml

automatically converts metafields

automatically converts metafields

---

punchbowl/data/tests/test_units.py
punchbowl/data/units.py

Brings in Marcus's fixed calculate_image_pixel_area and adds tests
It has tests!
Pixel areas are breakingly changed to be correct

Improve calculation of pixel areas

---

punchbowl/data/meta.py
punchbowl/data/tests/test_io.py
punchbowl/level1/despike.py
punchbowl/level1/flow.py
punchbowl/level1/tests/test_flow.py
punchbowl/level2/bright_structure.py
punchbowl/level2/flow.py
punchbowl/level2/merge.py
punchbowl/level2/polarization.py
punchbowl/level2/resample.py
punchbowl/level2/tests/test_flow.py
punchbowl/level2/tests/test_merge.py
punchbowl/level3/polarization.py
punchbowl/level3/tests/test_flow.py
punchbowl/util.py

- Fixes merging to not have gaps. 
- Adds tests for L2 and L3
- Always writes to tmpdir in tests
- Starts improving metadata propagation
- Allow != 12 images for L2 without crashing

Confirm l2 l3 tests

---

punchbowl/data/data/Level3.yaml
punchbowl/data/data/omniheader.csv
punchbowl/data/meta.py
punchbowl/data/tests/LevelTest.yaml
punchbowl/data/tests/omniheader.csv
punchbowl/data/tests/test_meta.py
punchbowl/level3/flow_velocity.py
punchbowl/level3/tests/test_velocity.py
punchbowl/level3/velocity.py

Adds flow tracking to the pipeline
closes #181

flow tracking

---

punchbowl/level3/f_corona_model.py

Don't use "build" version for imports... silly PyCharm.

fix import

---

.pre-commit-config.yaml
punchbowl/data/__init__.py
punchbowl/data/tests/test_io.py
punchbowl/level2/polarization.py
punchbowl/level2/tests/test_polarization.py

*What does this PR introduce?*

Updated Level2/polarization

---

punchbowl/level2/resample.py

When building trefoil mosaics, this PR finds the bounding box of each input image in the output frame, and only reprojects that region. This saves a lot of work for output pixels that never get filled anyway.
For a clear mosaic, the speed increase is from 1m27s to 60s.
I tested this with these files:
```
/d0/punchsoc/gamera_data/1/CR1/2024/11/25/PUNCH_L1_CR1_20241125155055_v1.fits
/d0/punchsoc/gamera_data/1/CR2/2024/11/25/PUNCH_L1_CR2_20241125155055_v1.fits
/d0/punchsoc/gamera_data/1/CR2/2024/11/25/PUNCH_L1_CR2_20241125155055_v1.fits
/d0/punchsoc/gamera_data/1/CR2/2024/11/25/PUNCH_L1_CR2_20241125155055_v1.fits
```
and for the output frame I took that of:
```
/d0/punchsoc/gamera_data/2/PTM/2024/11/25/PUNCH_L2_PTM_20241125155055_v1.fits
```
(Because the CTM hasn't been generated yet)
I got …

Make mosaics faster w/ bounding boxes

---

punchbowl/data/io.py

Ignore warnings in unpacking uncertainty

---

punchbowl/level1/despike.py
punchbowl/level1/flow.py
punchbowl/level1/tests/test_despike.py

adds thresholding to spike value replacement

adds thresholding to spike value replacement

---

README.md

adds a DOI badge, which should point to the latest release automatically.

adds DOI badge

---

docs/source/intro.rst

Adds python documentation, to close #184

Document python tutorials

---

punchbowl/data/tests/test_history.py
punchbowl/data/tests/test_io.py
punchbowl/data/tests/test_meta.py
punchbowl/data/tests/test_units.py
punchbowl/data/wcs.py
punchbowl/level1/tests/test_deficient_pixel.py
punchbowl/level1/tests/test_sqrt.py
punchbowl/level2/tests/test_bright_structure.py
punchbowl/level2/tests/test_merge.py
punchbowl/level2/tests/test_resample.py
punchbowl/level3/tests/test_f_corona_model.py
punchbowl/level3/tests/test_stellar.py
punchbowl/level3/tests/test_velocity.py
punchbowl/level3/velocity.py
scripts/generate_templates.py

Sets WCS array_shape throughout. Also fixes some ruff grumbling.

WCS array shape

---

docs/source/index.rst

remove broken link

---

punchbowl/data/io.py
punchbowl/data/tests/test_io.py

adds file provenance extname and test

adds file provenance extname and test

---

punchbowl/data/__init__.py
punchbowl/data/io.py

Quicklook generation

---

docs/conf.py

update copyright year

---

punchbowl/data/wcs.py

Change type hint to astropy time and not a datetime

---

.pre-commit-config.yaml
CHANGELOG.md
punchbowl/data/punch_io.py
punchbowl/data/sample.py
punchbowl/data/tests/test_visualize.py
punchbowl/data/visualize.py

Make the colormap a variable instead of just a function. 
@lowderchris we should make sure documents are updated accordingly.

Make cmap a variable

---

.pre-commit-config.yaml
CHANGELOG.md
punchbowl/data/sample.py
punchbowl/level1/psf.py

Creates the PSF building function to be used in punchpipe automatically.

Create a PSF building function

---

CHANGELOG.md
punchbowl/data/__init__.py
punchbowl/data/meta.py
punchbowl/data/punch_io.py
punchbowl/data/sample.py
punchbowl/data/tests/test_punch_io.py

Todo:
- @lowderchris please check my work
Here's an example output though:
(CL stands for clear not Chris Lowder haha and comes from the metadata)

Adds metadata display to quicklook images

---

CHANGELOG.md
punchbowl/data/punch_io.py
punchbowl/data/tests/test_punch_io.py

*What does this PR introduce?*
Changed default writing behavior of ndcubes to not overwrite
Closes #233

Change overwrite

---

CHANGELOG.md
punchbowl/data/data/omniheader.csv
punchbowl/data/tests/test_units.py
punchbowl/data/units.py
punchbowl/level1/flow.py
punchbowl/level1/initial_uncertainty.py
punchbowl/level1/sqrt.py
punchbowl/level1/tests/test_flow.py
punchbowl/level1/tests/test_sqrt.py

Splits gain correction to be done per half of the CCD chip.

computes gain correction per half ccd

---

CHANGELOG.md
punchbowl/data/data/omniheader.csv
punchbowl/level1/sqrt.py
punchbowl/level1/tests/test_sqrt.py

Adds scaling factor to square root decoding function.

Descaling data

---

CHANGELOG.md
punchbowl/level1/flow.py

Some changes to get PSF estimation running. At least some of this may have to do with the 1.0 release of `regularizepsf`

Some changes to get PSF estimation running

---

CHANGELOG.md
punchbowl/data/meta.py

Fix this error message. The message shows because the provided default isn't the right data type.

Fix error message

---

CHANGELOG.md
punchbowl/level1/vignette.py

It makes the vignetting correction work

Fixes to get vignetting running

---

CHANGELOG.md
punchbowl/level1/destreak.py
punchbowl/level1/flow.py
punchbowl/level1/psf.py
punchbowl/level1/quartic_fit.py
punchbowl/level1/vignette.py
pyproject.toml

Allows calibration files to be passed as callables that load the data
Speedups
Generated 100,000 L1 files

First batch of L1 Speedups

---

CHANGELOG.md
punchbowl/data/data/Level0.yaml
punchbowl/data/data/omniheader.csv
punchbowl/data/meta.py
punchbowl/data/tests/test_meta.py

- Updates units for astropy / sunpy unit compatibility
- Enforces FITS header compliance

Header updates

---

CHANGELOG.md
punchbowl/level1/flow.py

adds check for square root decompression

adds check for square root decompression

---

CHANGELOG.md
punchbowl/data/punch_io.py
pyproject.toml

adds metadata to output jpeg2000 files

adds metadata to output jpeg2000 files

---

CHANGELOG.md
punchbowl/data/meta.py
punchbowl/data/units.py
punchbowl/level1/alignment.py
punchbowl/level1/deficient_pixel.py
punchbowl/level1/despike.py
punchbowl/level1/destreak.py
punchbowl/level1/flow.py
punchbowl/level1/initial_uncertainty.py
punchbowl/level1/psf.py
punchbowl/level1/quartic_fit.py
punchbowl/level1/sqrt.py
punchbowl/level1/stray_light.py
punchbowl/level1/vignette.py
punchbowl/level2/resample.py
pyproject.toml

* Speeds up L1s
* Including by removing some logging calls to try to reduce the burden on the prefect database
* Fix L2 reprojection
* Upcasts `int`s to `float`s in `NormalizedMetadata`
Made a bunch of L1s

Final speedups for L1, plus NormalizedMetadata upcasting and L2 projection fix

---

punchbowl/level1/despike.py

added parenthesis to fix line 77 in despike.py fixing the error associated when setting up the dilation value

added parenthesis to fix line 77 in despike.py

---

CHANGELOG.md
punchbowl/data/punch_io.py
punchbowl/data/tests/test_punch_io.py

writes quicklook images as grayscale, with color flag option

writes quicklook images as grayscale, with color flag option

---

CHANGELOG.md
punchbowl/data/data/omniheader.csv
punchbowl/level1/sqrt.py

COMPBITS can be set to a floating-point value. See punch-mission/punchpipe#163

Allow floating-point COMPBITS

---

README.md
docs/data/access.rst
docs/data/data_object.rst
docs/intro.rst
docs/pipeline/design.rst
docs/pipeline/overview.rst

Cleans up a few inconsistencies in docs

---

CHANGELOG.md
punchbowl/exceptions.py
punchbowl/level1/sqrt.py
punchbowl/level1/tests/test_sqrt.py

manages square root decoding table value overflow

manages square root decoding table value overflow

---

CHANGELOG.md
docs/pipeline/level1/despike.rst

Updated the documentation of despike based on Astro-SCRAPPY algorithm.
Closes #467

Document astroscrappy

---

CHANGELOG.md
punchbowl/data/data/Level1.yaml
punchbowl/data/punch_io.py
punchbowl/data/wcs.py
punchbowl/level1/alignment.py
punchbowl/level1/flow.py
punchbowl/level1/psf.py
punchbowl/level1/quartic_fit.py
punchbowl/level1/stray_light.py
punchbowl/level1/vignette.py
punchbowl/util.py

This PR makes some changes to enable QuickPUNCH generation.

Prepare to make QuickPUNCH images

---

CHANGELOG.md
punchbowl/level1/initial_uncertainty.py
punchbowl/level1/tests/test_initial_uncertainty.py

For data pixels that are saturated, the uncertainty layer is now flagged as infinite uncertainty.

adds module and test for flagging in uncertainty of saturated pixels

---

CHANGELOG.md
punchbowl/data/data/Level0.yaml

adds data DOI for level 0 data

adds data DOI

---

CHANGELOG.md
punchbowl/data/punch_io.py

This will hopefully fix #484 
Watch existing tests pass
None
Closes #484

cast to float32 instead of 64

---

CHANGELOG.md
docs/data/data_codes.rst
docs/data/data_overview.rst

remove VAN from data_codes.rst

---

punchbowl/level1/flow.py

I know I reviewed the PR, but the change was to the wrong flow 😬

Use the new NFI mask for L1, not LH

---

docs/data/data_codes.rst

Adds the distortion product code. Resolves #474

Adds DS to product code table

---

punchbowl/data/data/Level1.yaml
punchbowl/data/meta.py
punchbowl/data/punch_io.py
punchbowl/exceptions.py
punchbowl/level1/alignment.py
punchbowl/level1/destreak.py
punchbowl/level1/sqrt.py
punchbowl/level1/tests/test_initial_uncertainty.py
punchbowl/levelq/pca.py
punchbowl/util.py

This reverts commit e7dbb88514fafd606db6c46788001e06e1ae8c0f.

Repairs develop branch after direct push

---

CHANGELOG.md
punchbowl/level2/flow.py
punchbowl/level2/tests/test_flow.py

This runs PTM and CTM through the same flow.
Also speeds up the L2 tests by not running them at 4k
*Please list tasks to complete this PR.*
Tests ✅

Pull request to UNify L2 Flows

---

CHANGELOG.md
punchbowl/level2/flow.py

`FILEVRSN` has to be propagated

Set FILEVRSN in L2s

---

CHANGELOG.md
punchbowl/level1/flow.py
punchbowl/level1/stray_light.py
punchbowl/level1/tests/test_stray_light.py
punchbowl/level3/f_corona_model.py
punchbowl/tests/test_util.py
punchbowl/util.py

Implements a rolling stray light model in conjunction with changes in punchpipe.

Implements rolling stray light model

---

.pre-commit-config.yaml
CHANGELOG.md
docs/pipeline/level1/pointing.rst
punchbowl/level1/alignment.py
punchbowl/level1/flow.py
punchbowl/level1/psf.py
punchbowl/level1/tests/test_flow.py
pyproject.toml

Implements new pointing refinement algorithm

---

CHANGELOG.md
punchbowl/level1/vignette.py

Updates the vignetting generator function, to perform an erosion operation on the WFI mask used in generation.

Update the vignetting generator function

---

changelog/538.breaking.rst
changelog/538.feature.rst
changelog/538.trivial.2.rst
changelog/538.trivial.rst
punchbowl/level1/flow.py
punchbowl/level1/psf.py
punchbowl/level1/quartic_fit.py
punchbowl/level1/stray_light.py
punchbowl/level1/vignette.py
punchbowl/prefect.py
punchbowl/util.py

* Stray light: set date_obs to the reference time, and cut memory use significantly
* Cache layer: use the `DataLoader` API everywhere---it's cleaner
* Log spam: only set the debugging `on_completion` hook if debug is enabled. This flow set-up code runs afresh in the new process every time a flow starts, so the debug state can still be changed live. But now we don't get log messages about the `on_completion` hook in non-debug mode.

Misc improvements

---

changelog/550.feature.rst
punchbowl/level1/sqrt.py
punchbowl/level1/tests/test_sqrt.py

Implements second order square root decoding table, using the technique from DeForest et al 2022.

implements second order square root decoding table

---

changelog/551.bugfix.rst
punchbowl/level1/flow.py
punchbowl/level1/tests/test_flow.py
punchbowl/level2/flow.py
punchbowl/level2/tests/test_flow.py
punchbowl/level3/flow.py

Adds filenames used to generate a file in Provenance HDU

Adds filenames in provenance

---

changelog/547.bugfix.rst
punchbowl/level1/psf.py

Increase psf dilation

---

changelog/560.trivial.rst
punchbowl/prefect.py

No task caching

---

changelog/562.trivial.rst
punchbowl/level1/flow.py

Don't need these steps if we're not aligning and not writing a Q file

Don't do work we won't use

---

changelog/568.bugfix.rst
changelog/568.feature.rst
punchbowl/level1/stray_light.py
punchbowl/util.py
pyproject.toml

We'll have to merge this with @lowderchris 's changes
* Speed up nan percentile
* cut memory use for stray light model uncertainty generation
* Set DATE for stray light models

Faster stray light

---

changelog/567.feature.rst
punchbowl/cli.py
punchbowl/level1/tests/test_vignette.py
punchbowl/level1/vignette.py
punchbowl/tests/test_cli.py
punchbowl/util.py

Integrates NFI flat-fielding code into punchbowl

NFI flat-fielding

---

changelog/586.bugfix.rst
punchbowl/level1/flow.py

We were just copying the value from the L0 file.

Set DATE in L1 files

---

changelog/597.feature.rst
examples/PUNCH-InSitu-Connection.py

Add `punchbowl/examples/PUNCH-InSitu-Connection.py`
Run github actions doc build
Works if docs build is successful
None
#596

Add spacecraft orbits example

---

changelog/595.bugfix.rst
punchbowl/data/meta.py
punchbowl/level1/alignment.py
punchbowl/level1/flow.py
punchbowl/level1/psf.py
punchbowl/levelq/f_corona_model.py
punchbowl/levelq/pca.py

updates quickpunch f-corona generation for multithreading and data cube array ordering...
...and makes some changes ruff demanded.

updates quickpunch f-corona generation

---

changelog/600.feature.rst
punchbowl/data/tests/test_visualize.py
punchbowl/data/visualize.py

creates inverse punch colormap, cmap_punch_r, that can also be imported from punchbowl.data.visualize

Creates inverse punch colormap

---

changelog/603.feature.rst
changelog/605.bugfix.rst
punchbowl/level3/f_corona_model.py
punchbowl/level3/stellar.py
punchbowl/level3/tests/test_flow.py

* Handle exceptions in data loading (they were not propagating back to Prefect, at least sometimes)
* Load more quickly
* Let CI pass

F corona quickfix

---

changelog/627.doc.rst
docs/data/data_anomalies.rst
docs/pipeline/level1/pointing.rst
docs/pipeline/level1/psf_correction.rst
docs/pipeline/level1/stray_light.rst
punchbowl/level1/alignment.py

Update documentation to match current status
