punch-mission/punchbowl

- .github/workflows/python-publish.yaml
- docs/source/conf.py
- punchbowl/data/io.py
- punchbowl/data/tests/test_io.py
- punchbowl/data/tests/test_visualize.py
- punchbowl/data/visualize.py
- punchbowl/level2/tests/test_bright_structure.py
- pyproject.toml
> adds visualization core

- punchbowl/data/wcs.py
Ran into this when testing a `remove_starfield` speedup---generated WCSes don't have their NAXISN keywords set, and therefore don't have `pixel_shape` or `array_shape`.  On the `remove_starfield` side that can and should and now is handled. But this seems like a might-as-well-have on the `punchbowl` side.
> When generating WCSes, set NAXIS/array_shape/etc.

- punchbowl/level3/stellar.py
Step 1 of speeding up starfield subtraction. This avoids looping over polarization components.
~The results of the before and after aren't exactly equal, but they're `np.allclose`, and I don't know why yet. The reprojected starfield samples appear to be `np.array_equal`, but the blurred input data is only `np.allclsoe`.~
I found the bug in my test setup. This PR produces bit-for-bit identical outputs.
Runtime appears to be 26 minutes before and 10 minutes after.
It seems to work on my machine
None
> Faster star subtraction

- punchbowl/level3/stellar.py
Handling uncertainty in the starfield subtraction was just subtracting the actual starfield from the uncertainty through a second call to `starfield_model.subtract_from_image`. Since it's still the same WCS and transformation, we might as well do it in the same call as for the actual starfield subtraction. That takes things from 10 min to 7m45s.
This does not address the question of what's correct for the uncertainty at this step. It was subtracting the actual starfield, and this PR takes the liberty of changing it to subtract the starfield's uncertainty. Still not correct, but maybe closer.
So the uncertainty comes out different, but the data layer comes out bit-for-bit identical.
> Reproject starfield sample and uncertainty in one fell swoop

- punchbowl/data/io.py
- punchbowl/level3/tests/test_celestial_intermediary.py
Before I realized that most of the starfield read-in time was decompression, I tried this. This saves 1.3 seconds for loading the starfield map (from 2 s to .7 s) by avoid memory allocations, but maybe saving a smidge of time for every FITS read-in will add up over the whole pipeline.
> Unpack uncertainties faster

- punchbowl/level2/resample.py
- punchbowl/level3/celestial_intermediary.py
I remembered last night that Astropy has pixel centers at integer coordinates, so the image actually starts at -0.5, not 0, and so when we find a bounding box for mosaic reprojection (and also in the celestial intermediary code), the points we position along the edges of the input image should be along (x,y) = -0.5.
This PR puts them at -1, just for good measure. (The other side was already at `shape[0]` or `shape[1]`, so it was already just a smidge past the actual edge which is at `shape[0] - 0.5`.)
I don't know why I'd originally set the points at (x,y) = 1 instead of (x,y) = 0. I'd count that as a bug, though it apparently wasn't affecting the test case I did yesterday.
This just makes the bounding box bigger, so it shouldn't affect anything.
> Be a little more accurate/safe with bounding boxes

- punchbowl/level2/resample.py
Last change, hopefully. Makes sure the slightly-offset edge values are used all around. Also tries to make it a bit more readable.
> Fully implement previous change to bounding boxes

- punchbowl/level1/stray_light.py
- punchbowl/level3/f_corona_model.py
- punchbowl/util.py
- Improves the `nan_percentile` function a bit
- Uses it for F-corona estimation
- Rolls the median into that percentile call
- Stops imputing fill values for the points that get smoothed out, instead letting them be nans that get filtered out in the cubic fit
This does not:
- Do the detrending we were looking at today
This should be a good deal faster, and should produce fewer weird values in the F-corona model because we're not using insufficient fill values for the smoothing.
> Better f corona

- punchbowl/data/meta.py
Adds WCS_OMITTED_KEYWORDS list to prevent duplicate timing header keywords (DATE-OBS, etc) when converting a normalizedmetadata object to a FITS header.
Will close #227
> adds wcs keywords to ignore to prevent duplication

- punchbowl/level3/stellar.py
- pyproject.toml
**This requires `remove_starfield` v0.0.4**
This makes a starfield map that doesn't curve up and down. This means less distortion (unsure if that affects the accuracy of the starfield subtraction) and should offer more speed for the map create (since not blowing things up at extreme declination ought to mean fewer output pixels to reprojection while still capturing everything). Likewise, since this should enable smaller maps, it ought to speed up the subtraction step where it's loading in the star map.
Before:
After:
None
Run it overnight
> Create starfield estimates that are less distorted

- punchbowl/level2/flow.py
- punchbowl/level3/f_corona_model.py
- punchbowl/levelq/f_corona_model.py
- punchbowl/levelq/flow.py
Separate QuickPUNCH out of main processing
> Separate quick punch

- punchbowl/level1/flow.py
- punchbowl/level1/tests/test_flow.py
- punchbowl/level1/tests/test_vignette.py
- punchbowl/level1/vignette.py
Disentangles vignetting from the quartic fit module, re-establishing it as a separate module and calibration input.
Closes #351
> return of vignetting

- .pre-commit-config.yaml
- CHANGELOG.md
- punchbowl/data/sample.py
There was an extra statement that cased a Ruff failure. This fixes that.
> Fixes ruff noqa statement

- punchbowl/data/tests/test_wcs.py
- punchbowl/data/wcs.py
- punchbowl/level2/resample.py
- punchbowl/level2/tests/test_flow.py
Here we go!
Two quirks to think about at some point
Run the tests!
None, but I think we should stop returning the P angle from `calculate_helio_wcs_from_celestial`
> Fix radec wcs

- punchbowl/level3/f_corona_model.py
- punchbowl/levelq/f_corona_model.py
- punchbowl/util.py
I'll wait to parallelize the nan-filling part of the F-corona generation until after we re-run things and see what the nan value distribution looks like. (A lot of nans were showing up because of the mis-assembled mosaics.) In the meantime, might as well get these other parts in.
This parallelizes the reading of input files and the building of the F-corona model.
I see now in your earlier commits in this branch `solve_qp_cube` was parallelized and then (mistakenly?) that was reverted. My version does it at a higher level in the call stack, so that the outlier rejection part is also in parallel.
This can wait for a future PR:
While we were in SLO I ran the code before and after this parallelization and got identical results.
None
This addresses part of #381
> Parallelize f corona

- CHANGELOG.md
- punchbowl/level1/flow.py
- punchbowl/level2/flow.py
- punchbowl/level2/resample.py
- punchbowl/level3/f_corona_model.py
- punchbowl/level3/flow.py
- punchbowl/level3/stellar.py
- punchbowl/levelq/f_corona_model.py
- punchbowl/prefect.py
All flows in punchbowl are now `punch_flow`s!
In the future, this will let us easily point them all at a central Dask task executor. (Taking advantage of that will probably require making sure all parallelizable tasks are `.submit()`ed.
Tests pass
> Create a punch_flow decorator

- CHANGELOG.md
- punchbowl/data/meta.py
- punchbowl/level1/flow.py
- punchbowl/level1/tests/test_flow.py
- punchbowl/level2/flow.py
- punchbowl/level3/f_corona_model.py
- punchbowl/util.py
- Detrending in F-corona estimation before outlier removal
- Read header values for gain and exposure time
- Enforce UTC for L2 date averaging, to avoid DST glitches
- Set FILEVRSN for L2s
> F-corona detrending, fixes for L2 metadata, and use header's gain and exposure time

- CHANGELOG.md
- punchbowl/data/meta.py
- punchbowl/data/punch_io.py
- punchbowl/levelq/flow.py
- punchbowl/levelq/pca.py
- punchbowl/util.py
- pyproject.toml
Adds NFI PCA filtering to LQ, and some changes to support it:
- When we're loading the thousand files to be fit, we don't need to spend time loading uncertainty or provenance
- Copy `FILEVRSN` from one of the input files into the LQ output
- Fix for `NormalizedMetadata` having strings inserted
It runs on 190
> Adds NFI PCA filtering to LQ

- CHANGELOG.md
- punchbowl/level1/flow.py
Makes the NFI mask avoid the occulter, outer edge, and pylon glint area for pointing refinement.
> For pointing refinement, we restrict the nfi mask

- CHANGELOG.md
- docs/conf.py
It's as simple as enabling a Sphinx extension, so I did it.
> Add button to view source in docs

- CHANGELOG.md
- punchbowl/level1/stray_light.py
This cuts the memory use of the stray light model generation by not keeping the `NDCube`s in memory in addition to the large data cube that stores all the images.
> Reduce memory use of stray light model generation

- CHANGELOG.md
- punchbowl/data/tests/test_punch_io.py
adds uncertainty to the test_write_punchdata_with_distortion test to allow passage
> adds uncertainty to test ndcube

- CHANGELOG.md
- punchbowl/level1/stray_light.py
Outside my notebook, we can't easily set the `write_ndcube_to_fits` flag to avoid computing a celestial WCS, so let's just use a full but arbitrary WCS for now.
> Make stray light run

- README.md
I like when packages call out contributors. Should we do something like this?
> Add contributors picture

- .gitignore
- changelog/546.bugfix.rst
- punchbowl/levelq/tests/test_pca.py
Ignores PCA testing on macOS (which is doomed to fail) and commands git to ignore sample PUNCH data downloaded as part of testing.
> Improvement of testing

- changelog/558.trivial.rst
- punchbowl/data/wcs.py
- pyproject.toml
Stop requiring error messages to be defined separately
> Turns off ruff EM101

- changelog/557.bugfix.rst
- punchbowl/level1/alignment.py
NFI pointing alignment was failing because of astrometry.net's initial solver. This was in part to incorrect search scales and also because of weird "non-stars" being detected as stars. We now try to use astrometry.net but if it fails we warn and proceed with the instrument WCS.
> Change NFI pointing alignment to work differently than WFI

- changelog/570.feature.rst
- punchbowl/level1/alignment.py
We can speed up the distance calculation tremendously by not trying to figure it out for every pair of coordinates.
> Speed up pointing by using KDTree
